SET LANGUAGE Turkish
------------------------
SELECT CITY,SUM(LINETOTAL) AS TOTALSALES FROM SALEORDERS
GROUP BY CITY 
ORDER BY CITY 
-----------------------
SELECT CITY,MONTH_,SUM(LINETOTAL) AS TOTALSALE FROM SALEORDERS
GROUP BY CITY,MONT
ORDER BY CITY 
-------------------------
SELECT CITY,DAYOFWEEK_, SUM(LINETOTAL) AS TOTALSALE 
FROM SALEORDERS
GROUP BY CITY,DAYOFWEEK_
ORDER BY CITY  
----------------------
SELECT 
DISTINCT CITY,
(SELECT SUM (LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND DAYOFWEEK_='Pazartesi') AS PAZARTESÝ,
(SELECT SUM (LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND DAYOFWEEK_='Salý') AS SALI,
(SELECT SUM (LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND DAYOFWEEK_='Çarþamba') AS ÇARÞAMBA, 
(SELECT SUM (LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND DAYOFWEEK_='Perþembe') AS PERÞEMBE, 
(SELECT SUM (LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND DAYOFWEEK_='Cuma') AS CUMA,
(SELECT SUM (LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND DAYOFWEEK_='Cumartesi') AS CUMARTESÝ,
(SELECT SUM (LINETOTAL) FROM SALEORDERS WHERE CITY=S.CITY AND DAYOFWEEK_='Pazar') AS PAZAR
FROM SALEORDERS S
GROUP BY CITY
ORDER BY CITY 
-------------------
SELECT S.CITY,S1.CATEGORY1,SUM(S1.TOTALSALE) AS TOTALSALE
FROM SALEORDERS S
CROSS APPLY  (SELECT TOP 5 CATEGORY1,SUM(LINETOTAL) AS TOTALSALE FROM SALEORDERS WHERE CITY=S.CITY GROUP BY CATEGORY1 ORDER BY 2 DESC) S1
GROUP BY S.CITY,S1.CATEGORY1,S1.TOTALSALE
ORDER BY S.CITY,SUM(S1.TOTALSALE) DESC   
-------------------
SELECT S.CITY , S1.CATEGORY1 , S2.CATEGORY2 ,SUM(S1.TOTALSALE)
FROM SALEORDERS S
CROSS APPLY (SELECT TOP 3 CATEGORY1,SUM(LINETOTAL) AS TOTALSALE FROM SALEORDERS WHERE CITY=S.CITY GROUP BY CATEGORY1 ) S1
CROSS APPLY (SELECT TOP 3 CATEGORY2,SUM(LINETOTAL) AS TOTALSALE FROM SALEORDERS WHERE CITY=S.CITY AND CATEGORY1=S1.CATEGORY1 GROUP BY CATEGORY2 ) S2
GROUP BY S.CITY, S1.CATEGORY1 , S2.CATEGORY2,S1.TOTALSALE,S2.TOTALSALE
ORDER BY 1,2,4 DESC 
------------------
SELECT S.BRAND,  S1.CATEGORY1,SUM(TOTALPRICE) AS TOTALPRICE
FROM SALEORDERS S
CROSS APPLY (SELECT DISTINCT CATEGORY1, BRAND,MAX(LINETOTAL) AS TOTALPRICE FROM SALEORDERS WHERE BRAND=S.BRAND GROUP BY BRAND ,LINETOTAL,CATEGORY1 ) S1
GROUP BY S.BRAND,S1.CATEGORY1
ORDER BY 1

SELECT * FROM ORDERDETAILS
SELECT * FROM SALEORDERS



